# Generated by Django 5.1.1 on 2024-09-21 01:30

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address", options={"verbose_name_plural": "Endereços"},
        ),
        migrations.AlterModelOptions(
            name="cartorder", options={"verbose_name_plural": "Pedidos"},
        ),
        migrations.AlterModelOptions(
            name="cartorderitem", options={"verbose_name_plural": "Itens do carrinho"},
        ),
        migrations.AlterModelOptions(
            name="category", options={"verbose_name_plural": "Categorias"},
        ),
        migrations.AlterModelOptions(
            name="product", options={"verbose_name_plural": "Produtos"},
        ),
        migrations.AlterModelOptions(
            name="productimages", options={"verbose_name_plural": "Imagens do produto"},
        ),
        migrations.AlterModelOptions(
            name="productreview",
            options={"verbose_name_plural": "Avaliações dos produtos"},
        ),
        migrations.AlterModelOptions(
            name="wishlist", options={"verbose_name_plural": "Lista de desejos"},
        ),
        migrations.RemoveField(model_name="product", name="image",),
        migrations.RemoveField(model_name="product", name="tags",),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(upload_to="category/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_amount",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="productimages",
            name="image",
            field=models.ImageField(upload_to=core.models.product_directory_path),
        ),
    ]
