# Generated by Django 5.1.1 on 2024-09-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="store/images/products"
            ),
        ),
    ]
