# Generated by Django 5.1.1 on 2024-09-15 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_product_picture"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="picture",),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="store/images/products/<django.db.models.query_utils.DeferredAttribute object at 0x0000020BA64258D0>/",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        to="store.product",
                    ),
                ),
            ],
        ),
    ]
